version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
    version_requirement_updates: 'increase_versions'
    default_labels:
      - 'internal'
